In [1]:
import pandas as pd

In [2]:
pd.DataFrame({'col1': [1,2,3,4,5],
               'col2': [45,56,47,35,32],
               'col3': 'Ajay kumar Verma Ineuron one'
             })  #convert dictionary into DataFrame

col1  col2                          col3
0     1    45  Ajay kumar Verma Ineuron one
1     2    56  Ajay kumar Verma Ineuron one
2     3    47  Ajay kumar Verma Ineuron one
3     4    35  Ajay kumar Verma Ineuron one
4     5    32  Ajay kumar Verma Ineuron one

In [3]:
'Ajay kumar Verma Ineuron one'.split()

['Ajay', 'kumar', 'Verma', 'Ineuron', 'one']

In [4]:
df = pd.DataFrame({'col1': [1,2,3,4,5],
               'col2': [45,56,47,35,32],
               'col3': 'Ajay kumar Verma Ineuron one'.split()
             })

In [5]:
df

col1  col2     col3
0     1    45     Ajay
1     2    56    kumar
2     3    47    Verma
3     4    35  Ineuron
4     5    32      one

In [6]:
df['col4'] = 1

In [7]:
df

col1  col2     col3  col4
0     1    45     Ajay     1
1     2    56    kumar     1
2     3    47    Verma     1
3     4    35  Ineuron     1
4     5    32      one     1

In [8]:
df['col4'] = df['col1']**2

In [9]:
df

col1  col2     col3  col4
0     1    45     Ajay     1
1     2    56    kumar     4
2     3    47    Verma     9
3     4    35  Ineuron    16
4     5    32      one    25

In [10]:
df['col5'] = df['col3'].str[0]

In [11]:
df

col1  col2     col3  col4 col5
0     1    45     Ajay     1    A
1     2    56    kumar     4    k
2     3    47    Verma     9    V
3     4    35  Ineuron    16    I
4     5    32      one    25    o

In [12]:
def test(a):
    return a**2

In [13]:
df['col4_4'] = df['col1'].apply(test)  #apply function as a mapper function

In [14]:
df

col1  col2     col3  col4 col5  col4_4
0     1    45     Ajay     1    A       1
1     2    56    kumar     4    k       4
2     3    47    Verma     9    V       9
3     4    35  Ineuron    16    I      16
4     5    32      one    25    o      25

In [18]:
def test1(a):
    if a == 'A':
        return 'A'
    else:
        return 'z'
    

In [19]:
df['col6'] = df['col5'].apply(test1)

In [20]:
df

col1  col2     col3  col4 col5  col4_4 col6
0     1    45     Ajay     1    A       1    A
1     2    56    kumar     4    k       4    z
2     3    47    Verma     9    V       9    z
3     4    35  Ineuron    16    I      16    z
4     5    32      one    25    o      25    z

In [21]:
df['col6_6'] = df['col5'].apply(lambda a: 'A' if a== 'A' else 'Z')

In [22]:
df

col1  col2     col3  col4 col5  col4_4 col6 col6_6
0     1    45     Ajay     1    A       1    A      A
1     2    56    kumar     4    k       4    z      Z
2     3    47    Verma     9    V       9    z      Z
3     4    35  Ineuron    16    I      16    z      Z
4     5    32      one    25    o      25    z      Z

In [23]:
df['col7'] = df['col3'].apply(len)

In [24]:
df

col1  col2     col3  col4 col5  col4_4 col6 col6_6  col7
0     1    45     Ajay     1    A       1    A      A     4
1     2    56    kumar     4    k       4    z      Z     5
2     3    47    Verma     9    V       9    z      Z     5
3     4    35  Ineuron    16    I      16    z      Z     7
4     5    32      one    25    o      25    z      Z     3

In [25]:
import math

In [26]:
df['col8'] = df['col2'].apply(math.log)

In [27]:
df

col1  col2     col3  col4 col5  col4_4 col6 col6_6  col7      col8
0     1    45     Ajay     1    A       1    A      A     4  3.806662
1     2    56    kumar     4    k       4    z      Z     5  4.025352
2     3    47    Verma     9    V       9    z      Z     5  3.850148
3     4    35  Ineuron    16    I      16    z      Z     7  3.555348
4     5    32      one    25    o      25    z      Z     3  3.465736

# Numpy

In [28]:
import numpy as np

In [29]:
l = ['Ajay',2,3,4,5]

In [30]:
type(l)

list

In [31]:
np.array(l)

array(['Ajay', '2', '3', '4', '5'], dtype='<U21')

In [32]:
type(np.array(l))

numpy.ndarray

In [33]:
np.array([3,4,5,6,7,3.0])

array([3., 4., 5., 6., 7., 3.])

In [36]:
a = np.array([[1,2],[3,4]])

In [37]:
a

array([[1, 2],
       [3, 4]])

In [39]:
a[1]

array([3, 4])

In [40]:
a[1][1]

4

In [41]:
a1 = np.array([3,4,5,6,7,3.0])

In [42]:
a1

array([3., 4., 5., 6., 7., 3.])

In [43]:
a1[1]

4.0

In [50]:
np.array([1,2,3,4],ndmin = 2)

array([[1, 2, 3, 4]])

In [51]:
a2 = np.array([1,2,3,4],ndmin = 4)

In [52]:
a2

array([[[[1, 2, 3, 4]]]])

In [53]:
a2[0]

array([[[1, 2, 3, 4]]])

In [54]:
a2[0][0]

array([[1, 2, 3, 4]])

In [57]:
a2[0][0][0][0]

1

In [63]:
np.mat([1,2,3,4,5]) #mat gives min 2 dimension array

matrix([[1, 2, 3, 4, 5]])

In [61]:
np.asanyarray([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [64]:
a = [1,2,3,4,5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [65]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [66]:
np.asanyarray(np.mat(a)) #mat will convert only if its not 2Dim if it is already then it wont convert

matrix([[1, 2, 3, 4, 5]])

In [67]:
np.fromfunction(lambda i,j : i == j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [69]:
np.fromfunction(lambda i,j : i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [70]:
np.fromfunction(lambda i,j : i*j,(4,4),dtype = int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [75]:
#np.mat(np.fromfunction(lambda i,j,z : i*j*z,(3,3,2),dtype = int)) #error

In [76]:
np.fromfunction(lambda i,j,z : i*j*z, (3,3,2), dtype = int) # 3 matrix -> 3row X 2col

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [77]:
np.fromfunction(lambda i,j,z : i*j*z, (4,3,2), dtype = int) # 4 matrix -> 3row X 2col - 4Z-3Y-2X

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [79]:
np.fromfunction(lambda i,j,z,p : i*j*z*p, (4,3,2,2), dtype = int) # [4 matrix -> [ 3matrix -> [2row X 2col] ]]

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [102]:
a = np.fromfunction(lambda i,j,z : i*j*z, (4,3,2), dtype = int)

In [103]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [83]:
a.ndim #dimension

3

In [84]:
a.size #size - number of element

24

In [85]:
a.shape

(4, 3, 2)

In [104]:
a.reshape(12,2) # a.reshape(1,24)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 4],
       [0, 0],
       [0, 3],
       [0, 6]])

In [105]:
pd.DataFrame(a.reshape(8,3))

0  1  2
0  0  0  0
1  0  0  0
2  0  0  0
3  1  0  2
4  0  0  0
5  2  0  4
6  0  0  0
7  3  0  6

In [106]:
a.reshape(4,2,1,3)

array([[[[0, 0, 0]],

        [[0, 0, 0]]],


       [[[0, 0, 0]],

        [[1, 0, 2]]],


       [[[0, 0, 0]],

        [[2, 0, 4]]],


       [[[0, 0, 0]],

        [[3, 0, 6]]]])

In [107]:
a.reshape(4,2,1,3,1,1)

array([[[[[[0]],

          [[0]],

          [[0]]]],



        [[[[0]],

          [[0]],

          [[0]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[1]],

          [[0]],

          [[2]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[2]],

          [[0]],

          [[4]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[3]],

          [[0]],

          [[6]]]]]])

In [108]:
a.reshape(4,-1) # (4,6) 4*6=24 like 4 and -1 is rest so 4*6=24

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [109]:
a.reshape(4,-12323)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [110]:
a.reshape(2,4,-123)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 2]],

       [[0, 0, 0],
        [2, 0, 4],
        [0, 0, 0],
        [3, 0, 6]]])

In [86]:
a.dtype

dtype('int64')

In [87]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [88]:
a = np.fromfunction(lambda i,j : i*j, (4,3), dtype = int)

In [90]:
pd.DataFrame(a)

0  1  2
0  0  0  0
1  0  1  2
2  0  2  4
3  0  3  6

In [94]:
a = np.fromfunction(lambda i,j : i*j, (100,100), dtype = int)

In [95]:
pd.DataFrame(a)

0   1    2    3    4    5    6    7    8    9   ...    90    91    92  \
0    0   0    0    0    0    0    0    0    0    0  ...     0     0     0   
1    0   1    2    3    4    5    6    7    8    9  ...    90    91    92   
2    0   2    4    6    8   10   12   14   16   18  ...   180   182   184   
3    0   3    6    9   12   15   18   21   24   27  ...   270   273   276   
4    0   4    8   12   16   20   24   28   32   36  ...   360   364   368   
..  ..  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   
95   0  95  190  285  380  475  570  665  760  855  ...  8550  8645  8740   
96   0  96  192  288  384  480  576  672  768  864  ...  8640  8736  8832   
97   0  97  194  291  388  485  582  679  776  873  ...  8730  8827  8924   
98   0  98  196  294  392  490  588  686  784  882  ...  8820  8918  9016   
99   0  99  198  297  396  495  594  693  792  891  ...  8910  9009  9108   

      93    94    95    96    97    98    99  
0      0     0     0     0     0     0     0  
1     93    94    95    96    97    98    99  
2    186   188   190   192   194   196   198  
3    279   282   285   288   291   294   297  
4    372   376   380   384   388   392   396  
..   ...   ...   ...   ...   ...   ...   ...  
95  8835  8930  9025  9120  9215  9310  9405  
96  8928  9024  9120  9216  9312  9408  9504  
97  9021  9118  9215  9312  9409  9506  9603  
98  9114  9212  9310  9408  9506  9604  9702  
99  9207  9306  9405  9504  9603  9702  9801  

[100 rows x 100 columns]

In [96]:
np.random.rand(100,4) #rand -> it will give simple random number

array([[0.1962507 , 0.47688828, 0.44656447, 0.98953128],
       [0.73305727, 0.67522242, 0.2800437 , 0.56046016],
       [0.70553056, 0.17562959, 0.99571418, 0.55829108],
       [0.97545203, 0.87573824, 0.94010821, 0.61720162],
       [0.03734937, 0.50278051, 0.83788534, 0.32755899],
       [0.81184556, 0.56584182, 0.29554713, 0.6059666 ],
       [0.85341874, 0.33438604, 0.72256257, 0.84725582],
       [0.49117871, 0.57079904, 0.54445081, 0.1957564 ],
       [0.77704057, 0.50030191, 0.91403282, 0.80083011],
       [0.6289244 , 0.21984137, 0.90586383, 0.78666751],
       [0.2978657 , 0.29093449, 0.85554994, 0.15567688],
       [0.4000841 , 0.79955886, 0.30787472, 0.81199471],
       [0.42299512, 0.5209172 , 0.25210884, 0.16500729],
       [0.24327898, 0.8181957 , 0.44029428, 0.26579455],
       [0.57888107, 0.75526152, 0.83350031, 0.32348991],
       [0.86003057, 0.36315616, 0.3952101 , 0.58595437],
       [0.99842708, 0.41853667, 0.09213008, 0.18540342],
       [0.91923661, 0.2706045 ,

In [98]:
np.random.randint(4,50) #any random integer between 4-50

13

In [100]:
np.random.randn(4,5) #randn ->random number with normal distribution

array([[ 0.76496649,  0.67874976, -0.72255941, -0.94279548, -0.01025047],
       [-0.07029737,  0.39223547,  0.46253127,  1.47819056,  0.77670826],
       [ 0.85798431, -1.29435036,  0.58315259, -1.42470359, -0.29124883],
       [-1.38527802, -1.22960329,  0.82461941,  2.18548314, -0.62263887]])

In [101]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0  0.541542 -0.286764 -1.356198  0.863039 -1.687202
1  0.519832 -0.200214 -0.646288 -0.136363 -0.499515
2 -2.372328  1.795897  0.384814  0.187329 -0.644642
3  0.617545 -0.298988  1.820391 -1.325681 -0.605908

In [111]:
list(range(4,10)) #excluding 10

[4, 5, 6, 7, 8, 9]

In [112]:
list(range(4,10,2)) 

[4, 6, 8]

In [113]:
list(range(4,10,.2))  #only integer all 3paramenter

TypeError: 'float' object cannot be interpreted as an integer

In [114]:
np.arange(4,10,.2)

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [115]:
np.arange(4,10.5,.2)

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [116]:
a1 = np.arange(4,10.5,.2)

In [117]:
a1

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [118]:
a1[1:4]

array([4.2, 4.4, 4.6])

In [119]:
arr = np.random.rand(4,5)

In [120]:
arr

array([[0.08829811, 0.49934326, 0.5737143 , 0.23107651, 0.73297326],
       [0.30707822, 0.4783286 , 0.24517991, 0.56262994, 0.47335355],
       [0.33949327, 0.68894682, 0.6553466 , 0.53236113, 0.10988094],
       [0.81077073, 0.5125414 , 0.44358764, 0.41969119, 0.32568247]])

In [121]:
arr > .5

array([[False, False,  True, False,  True],
       [False, False, False,  True, False],
       [False,  True,  True,  True, False],
       [ True,  True, False, False, False]])

In [122]:
arr[arr > .5]

array([0.5737143 , 0.73297326, 0.56262994, 0.68894682, 0.6553466 ,
       0.53236113, 0.81077073, 0.5125414 ])

In [123]:
arr

array([[0.08829811, 0.49934326, 0.5737143 , 0.23107651, 0.73297326],
       [0.30707822, 0.4783286 , 0.24517991, 0.56262994, 0.47335355],
       [0.33949327, 0.68894682, 0.6553466 , 0.53236113, 0.10988094],
       [0.81077073, 0.5125414 , 0.44358764, 0.41969119, 0.32568247]])

In [126]:
arr[[1,2],[2]]

array([0.24517991, 0.6553466 ])

In [127]:
arr = np.random.rand(8,5)

In [128]:
arr

array([[0.81764033, 0.68276159, 0.88383718, 0.20379102, 0.27915745],
       [0.60978191, 0.0191832 , 0.05577631, 0.33004131, 0.34826243],
       [0.63248264, 0.07446326, 0.85107014, 0.59782537, 0.37513522],
       [0.10879188, 0.85667419, 0.31927387, 0.93623144, 0.51562836],
       [0.86539054, 0.50549064, 0.63709281, 0.05173101, 0.46557927],
       [0.53747751, 0.42408789, 0.33462   , 0.95363652, 0.39617582],
       [0.60833612, 0.18385769, 0.52748433, 0.41868704, 0.54047844],
       [0.81908004, 0.50705148, 0.78777452, 0.70439303, 0.68263219]])

In [130]:
arr[1:8,0:3]

array([[0.60978191, 0.0191832 , 0.05577631],
       [0.63248264, 0.07446326, 0.85107014],
       [0.10879188, 0.85667419, 0.31927387],
       [0.86539054, 0.50549064, 0.63709281],
       [0.53747751, 0.42408789, 0.33462   ],
       [0.60833612, 0.18385769, 0.52748433],
       [0.81908004, 0.50705148, 0.78777452]])

In [133]:
ar2 = arr[1:8,[0,1,2]]

In [134]:
ar2

array([[0.60978191, 0.0191832 , 0.05577631],
       [0.63248264, 0.07446326, 0.85107014],
       [0.10879188, 0.85667419, 0.31927387],
       [0.86539054, 0.50549064, 0.63709281],
       [0.53747751, 0.42408789, 0.33462   ],
       [0.60833612, 0.18385769, 0.52748433],
       [0.81908004, 0.50705148, 0.78777452]])

In [136]:
ar2[0][0] = 100

In [138]:
ar2

array([[1.00000000e+02, 1.91832024e-02, 5.57763053e-02],
       [6.32482637e-01, 7.44632627e-02, 8.51070140e-01],
       [1.08791883e-01, 8.56674188e-01, 3.19273866e-01],
       [8.65390542e-01, 5.05490640e-01, 6.37092814e-01],
       [5.37477510e-01, 4.24087887e-01, 3.34619999e-01],
       [6.08336116e-01, 1.83857686e-01, 5.27484331e-01],
       [8.19080040e-01, 5.07051480e-01, 7.87774516e-01]])

In [139]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[4,5]])


In [140]:
a

array([[1, 2],
       [3, 4]])

In [141]:
b

array([[2, 3],
       [4, 5]])

In [142]:
a*b #not multiplication matrix

array([[ 2,  6],
       [12, 20]])

In [148]:
m = a@b #matrix multiplication

In [149]:
m

array([[10, 13],
       [22, 29]])

In [150]:
m/0

/tmp/ipykernel_14955/3791875896.py:1: RuntimeWarning: divide by zero encountered in divide
  m/0


array([[inf, inf],
       [inf, inf]])